spring.application.name=fuel-tracker
server.port=8081

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FuelTrackerDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=yourpassword

logging.config=classpath:log4j2.xml

