spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=companyDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=admin@123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
server.port=8081
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
