spring.application.name=spring-db-switch

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=school;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=admin@123


postgres.url=jdbc:postgresql://localhost:5000/studentdb
postgres.username=postgres
postgres.password=kishor


app.use-sqlserver=false

