spring.application.name=company-backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=companyDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=admin@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port=8080


