spring.application.name=fuel-tracker
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FuelTrackerDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=admin@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ====== LOGGING CONFIG ======
# Set root log level
logging.level.root=INFO

# Custom package logging (optional)
logging.level.com.example.fueltracker=DEBUG

# Console logging format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%t] %logger{36} - %msg%n

# File logging
logging.file.name=logs/fueltracker.log
logging.file.path=logs
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10

# Disable banner (optional)
spring.main.banner-mode=off


