spring.application.name=StudentRegistrationApp
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=school;encrypt=false
spring.datasource.username=sa
spring.datasource.password=admin@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Optional: show SQL queries
spring.jpa.show-sql=true
server.port=8080

